def letter_printer():
    char = "#"
    print(f"{char*4}")
    print(f"{char}")
    print(f"{char}")
    print(f"{char}")
    print(f"{char*4}")
    print("")
    print("")
    print(f" {char*3} ")
    print(f"{char}    {char}")
    print(f"{char}    {char}")
    print(f"{char}    {char}")
    print(f" {char*3} ")
    print("")
    print("")
    print(f" {char*2} ")
    print(f"{char}  {char}")
    print(f"{char}   {char}")
    print(f"{char}    {char}")
    print(f"{char}   {char}")
    print(f"{char}  {char}")
    print(f"{char*3} ")
    print("")
    print("")
    print(f"{char*4}")
    print(f"{char}")
    print(f"{char}")
    print(f"{char*3}")
    print(f"{char}")
    print(f"{char}")
    print(f"{char*4}")

letter_printer()

    
